### ISSUE TITLE
Idea: Support AWS S3

### ISSUE THREAD

**Issue by svengau** [QubitProducts/gcs-browser-upload#15]
Hi, 
Great library. Out of the box, it also works great with AWS S3, with one minor change: S3 doesn't like to have the header "Content-Range" in the PUT request (Error 501).

I fully understand that this library is dedicated to GCS, but you could easily add S3 support.

It's not a feature request, just an idea to discuss.

**Comment by oliverwoodings** [comment]
@svengau thanks for the suggestion. We are not currently actively developing this package, since we don't use it ourselves anymore. I am more than happy to accept pull requests, however, if you would like to make one!

**Comment by svengau** [comment]
I'm afraid it will imply some unexpected support, and I would not have time to do it properly, so I prefer to close discussion.
